# Generated by Django 4.2.30 on 2024-01-20 12:00

from django.db import migrations


def add_ldap_configuration(apps, schema_editor):
    """Add LDAP configuration keys to InstanceConfiguration"""
    
    # Get the model from the apps registry (historical state)
    InstanceConfiguration = apps.get_model('plane.license', 'InstanceConfiguration')
    
    # LDAP configuration keys with default values
    ldap_configs = [
        {"key": "IS_LDAP_ENABLED", "value": "0", "category": "authentication", "is_encrypted": False},
        {"key": "LDAP_SERVER_URL", "value": "", "category": "authentication", "is_encrypted": False},
        {"key": "LDAP_PORT", "value": "389", "category": "authentication", "is_encrypted": False},
        {"key": "LDAP_BIND_DN", "value": "", "category": "authentication", "is_encrypted": False},
        {"key": "LDAP_BIND_PASSWORD", "value": "", "category": "authentication", "is_encrypted": True},
        {"key": "LDAP_BASE_DN", "value": "", "category": "authentication", "is_encrypted": False},
        {"key": "LDAP_USER_FILTER", "value": "(uid={username})", "category": "authentication", "is_encrypted": False},
        {"key": "LDAP_USE_SSL", "value": "0", "category": "authentication", "is_encrypted": False},
        {"key": "LDAP_ATTR_USERNAME", "value": "uid", "category": "authentication", "is_encrypted": False},
        {"key": "LDAP_ATTR_EMAIL", "value": "mail", "category": "authentication", "is_encrypted": False},
        {"key": "LDAP_ATTR_FIRST_NAME", "value": "givenName", "category": "authentication", "is_encrypted": False},
        {"key": "LDAP_ATTR_LAST_NAME", "value": "sn", "category": "authentication", "is_encrypted": False},
    ]
    
    # Create configuration entries if they don't exist
    for config in ldap_configs:
        InstanceConfiguration.objects.get_or_create(
            key=config["key"],
            defaults={
                "value": config["value"],
                "category": config["category"],
                "is_encrypted": config["is_encrypted"],
            }
        )


def remove_ldap_configuration(apps, schema_editor):
    """Remove LDAP configuration keys from InstanceConfiguration"""
    
    # Get the model from the apps registry (historical state)
    InstanceConfiguration = apps.get_model('plane.license', 'InstanceConfiguration')
    
    ldap_keys = [
        "IS_LDAP_ENABLED",
        "LDAP_SERVER_URL", 
        "LDAP_PORT",
        "LDAP_BIND_DN",
        "LDAP_BIND_PASSWORD",
        "LDAP_BASE_DN",
        "LDAP_USER_FILTER",
        "LDAP_USE_SSL",
        "LDAP_ATTR_USERNAME",
        "LDAP_ATTR_EMAIL",
        "LDAP_ATTR_FIRST_NAME",
        "LDAP_ATTR_LAST_NAME",
    ]
    
    # Remove configuration entries
    InstanceConfiguration.objects.filter(key__in=ldap_keys).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0121_alter_estimate_type'),
        ('license', '0006_instance_is_current_version_deprecated'),
    ]

    operations = [
        migrations.RunPython(add_ldap_configuration, remove_ldap_configuration),
    ]