# Generated by Django 4.2.28 on 2026-04-23 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0122_dashboard_feature'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='IssueWorklog',
                    fields=[
                        ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                        ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                        ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                        ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                        ('duration', models.IntegerField(default=0)),
                        ('date', models.DateField()),
                        ('description', models.TextField(blank=True, default='')),
                        ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                        ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worklogs', to='db.issue')),
                        ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_issueworklog', to='db.project')),
                        ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                        ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worklogs', to=settings.AUTH_USER_MODEL)),
                        ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_issueworklog', to='db.workspace')),
                    ],
                    options={
                        'verbose_name': 'Issue Worklog',
                        'verbose_name_plural': 'Issue Worklogs',
                        'db_table': 'issue_worklogs',
                        'ordering': ('-date', '-created_at'),
                    },
                ),
            ],
            database_operations=[
                # Table already exists in the database from a previous run.
                # This migration only updates Django's internal migration state tracker.
            ],
        ),
    ]
