# Generated by Django 4.2.28 on 2026-04-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0125_project_update_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='milestone_view',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_update_view',
            field=models.BooleanField(default=True),
        ),
    ]
