name: Build and Publish Caava Group Images

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_PREFIX: ${{ github.repository_owner }}/caava

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        include:
          - service: web
            dockerfile: ./apps/web/Dockerfile.web
            context: .
          - service: admin
            dockerfile: ./apps/admin/Dockerfile.admin
            context: .
          - service: space
            dockerfile: ./apps/space/Dockerfile.space
            context: .
          - service: live
            dockerfile: ./apps/live/Dockerfile.live
            context: .
          - service: api
            dockerfile: apps/api/Dockerfile.api
            context: ./apps/api
          - service: proxy
            dockerfile: ./apps/proxy/Dockerfile.ce
            context: ./apps/proxy

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_PREFIX }}-${{ matrix.service }}
          tags: |
            type=raw,value=latest
            type=sha

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            DOCKER_BUILDKIT=1
